### ISSUE TITLE
Service launch issue (arm64) : 'alembic' has no attribute 'migration'

### ISSUE THREAD

**Issue by vaidls** [marcus67/little_brother#154] opened 2021-09-12 15:37 UTC
Looks like I have issue to instal latest release:
1437324B  little-brother_0.4.8_107.deb
Linux version 4.19.0-17-arm64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.194-3 (2021-07-18)
MemTotal:         226084 kB

Specifics:
1. Install on clean Debian 10 after update,
2. ARM64 hardware

@little-brother:~$ sudo cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

@little-brother:~$ sudo tail -n 39 /var/log/little-brother/LittleBrother.log
2021-09-12 17:12:58,829 - root - INFO - Terminated with exit code 1
2021-09-12 17:23:33,978 - root - INFO - Started logging in CWD=/ using module python_base_app.log_handling
2021-09-12 17:23:33,985 - Configuration - INFO - Reading configuration file from '/etc/little-brother/little-brother.config'
2021-09-12 17:23:33,989 - Persistence - INFO - Database URL for normal access: 'sqlite://var/spool/little-brother/little-brother.sqlite.db'
2021-09-12 17:23:34,073 - Persistence - INFO - Checking whether to create database 'little_brother'...
2021-09-12 17:23:34,073 - App - INFO - Upgrading database to revision 'head' using alembic with working directory /var/lib/little-brother/virtualenv/lib/python3.7/site-packages/little_brother...
2021-09-12 17:23:34,122 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-09-12 17:23:34,123 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-09-12 17:23:34,135 - root - INFO - Starting daemon process...
2021-09-12 17:23:34,135 - App - INFO - Daemon starten...
2021-09-12 17:23:34,159 - App - INFO - Daemon gestarted
2021-09-12 17:23:34,165 - App - INFO - Starting app 'LittleBrother'
2021-09-12 17:23:34,167 - Persistence - INFO - Database URL for normal access: 'sqlite://var/spool/little-brother/little-brother.sqlite.db'
2021-09-12 17:23:34,192 - App - ERROR - Error 'module 'alembic' has no attribute 'migration'' in basic_init()
2021-09-12 17:23:34,192 - App - ERROR - Exception 'module 'alembic' has no attribute 'migration'' in run()
2021-09-12 17:23:34,192 - App - INFO - Shutting down services -- START
2021-09-12 17:23:34,192 - App - INFO - Shutting down services -- END
2021-09-12 17:23:34,201 - root - CRITICAL - module 'alembic' has no attribute 'migration'
2021-09-12 17:23:34,214 - root - ERROR - Stack trace =   File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/base_app.py", line 591, in main
    app.start()
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/daemon.py", line 178, in start
    self.run(*args, **kwargs)
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/base_app.py", line 483, in run
    raise previous_exception
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/base_app.py", line 463, in run
    self.basic_init()
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/base_app.py", line 449, in basic_init
    raise e
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/python_base_app/base_app.py", line 444, in basic_init
    self.prepare_services(p_full_startup=p_full_startup)
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/little_brother/app.py", line 243, in prepare_services
    self.check_migrations()
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/little_brother/app.py", line 174, in check_migrations
    current_version = db_mig.get_current_version()
  File "/var/lib/little-brother/virtualenv/lib/python3.7/site-packages/little_brother/db_migrations.py", line 61, in get_current_version
    context = alembic.migration.MigrationContext.configure(self._persistence.get_connection())

2021-09-12 17:23:34,214 - root - INFO - Terminated with exit code 1
vaidls@little-brother:~$

**Comment by marcus67** [comment] 2021-09-13 21:15
Hi Vaidls, thank your for reporting this bug. After my first analysis, I'm pretty confident that the error was caused by a new version of the Python package `alembic` which does not seem to be downward compatible. I will fix the version at 1.5.8 at see what happens. Stay tuned.

**Comment by vaidls** [comment] 2021-09-14 13:53
Thanks

__________________________
M. Vaidotas DILYS
France
mobile: +33 6 88 97 38 98
__________________________

**Comment by marcus67** [comment] 2021-09-15 21:12
Closed in 96288f178a68ffbdb3cac90f49a6a87ed1e0b386. Please try latest version 0.4.9.

**Closed by marcus67** 2021-09-15 21:12 UTC
Labels: bug, high priority

**Comment by vaidls** [comment] 2021-09-16 14:19
Thanks

__________________________
M. Vaidotas DILYS
France
mobile: +33 6 88 97 38 98
__________________________
