### ISSUE TITLE
debug_mode=True causes crash of client and/or server

### ISSUE THREAD

**Issue by MrFly** [marcus67/little_brother#112] opened 2021-01-18 10:56 UTC
The upgrade on client side failed with the following error:

```
2021-01-18 11:52:33,079 - root - INFO - Started logging in CWD=/ using module python_base_app.log_handling
2021-01-18 11:52:33,081 - Configuration - INFO - Reading configuration file from '/etc/little-brother/little-brother.config'
2021-01-18 11:52:33,082 - root - INFO - Set logging level to DEBUG
2021-01-18 11:52:33,082 - Persistence - INFO - Database URL for normal access: 'sqlite://var/spool/little-brother/little-brother.sqlite.db'
2021-01-18 11:52:33,092 - Persistence - INFO - Checking whether to create database little_brother...
2021-01-18 11:52:33,093 - App - INFO - Upgrading database to revision 'head' using alembic with working directory /var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother...
2021-01-18 11:52:33,114 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-01-18 11:52:33,114 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-01-18 11:52:33,118 - root - INFO - Starting daemon process...
2021-01-18 11:52:33,118 - App - INFO - Daemon starten...
2021-01-18 11:52:33,124 - App - INFO - Daemon gestarted
2021-01-18 11:52:33,125 - App - INFO - Starting app 'LittleBrother'
2021-01-18 11:52:33,126 - Persistence - INFO - Database URL for normal access: 'sqlite://var/spool/little-brother/little-brother.sqlite.db'
2021-01-18 11:52:33,139 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-01-18 11:52:33,139 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-01-18 11:52:33,143 - App - INFO - Database is on alembic version version_0_3
2021-01-18 11:52:33,325 - Persistence - INFO - Open database for normal access
2021-01-18 11:52:33,348 - App - INFO - Module python_base_app is using Babel translations in /var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/translations
2021-01-18 11:52:33,348 - UnixUserHandler - INFO - Using admin user 'None'
2021-01-18 11:52:33,361 - AppControl - INFO - Watching usernames: xxx
2021-01-18 11:52:33,361 - App - WARNING - Slave instance will not start web server due to missing port number
2021-01-18 11:52:33,362 - AppControl - INFO - Starting application in SLAVE mode communication with master at URL http://192.168.178.10:5555/api
2021-01-18 11:52:33,362 - AppControl - DEBUG - Queue for send: AdminEvent (type=START_CLIENT, host=yyy, user=None, process=None, PID=-)
2021-01-18 11:52:33,362 - AppControl - INFO - Using fully qualified domain name 'yyy' for process infos
2021-01-18 11:52:33,363 - App - DEBUG - Executing task app_control.scan_processes(ProcessHandler) 0.001 [s] behind schedule... *** START ***
2021-01-18 11:52:33,371 - ClientProcessHandler - DEBUG - Scanning processes...
2021-01-18 11:52:33,411 - App - DEBUG - Executing task app_control.scan_processes(ProcessHandler) 0.001 [s] behind schedule... *** END ***
2021-01-18 11:52:33,412 - App - DEBUG - Executing task app_control.scan_processes(DeviceHandler) 0.051 [s] behind schedule... *** START ***
2021-01-18 11:52:33,430 - App - DEBUG - Executing task app_control.scan_processes(DeviceHandler) 0.051 [s] behind schedule... *** END ***
2021-01-18 11:52:33,431 - App - DEBUG - Executing task app_control.check 0.069 [s] behind schedule... *** START ***
2021-01-18 11:52:33,431 - AppControl - WARNING - Cannot find user information for user 'xxx', will retry later...
2021-01-18 11:52:33,432 - MasterConnector - DEBUG - Executing POST API call 'http://192.168.178.10:5555/api/events'
2021-01-18 11:52:33,496 - AppControl - DEBUG - Queue locally: AdminEvent (type=PROCESS_START, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 11:52:33,497 - AppControl - DEBUG - Queue locally: AdminEvent (type=SPEAK, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 11:52:33,497 - AppControl - DEBUG - Processing AdminEvent (type=PROCESS_START, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 11:52:33,498 - App - WARNING - Propagating exception due to debug_mode=True
2021-01-18 11:52:33,498 - App - ERROR - Exception ''NoneType' object has no attribute 'handle_event_process_start'' in run()
2021-01-18 11:52:33,498 - App - INFO - Shutting down services -- START
2021-01-18 11:52:33,498 - AppControl - INFO - Artificially terminating 0 active processes on ClientProcessHandler
2021-01-18 11:52:33,498 - AppControl - INFO - Artificially terminating 0 active processes on ClientDeviceHandler
2021-01-18 11:52:33,498 - AppControl - DEBUG - Processing AdminEvent (type=SPEAK, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 11:52:33,513 - MasterConnector - DEBUG - Executing POST API call 'http://192.168.178.10:5555/api/events'
2021-01-18 11:52:33,523 - App - INFO - Shutting down services -- END
2021-01-18 11:52:33,523 - root - CRITICAL - 'NoneType' object has no attribute 'handle_event_process_start'
2021-01-18 11:52:33,524 - root - ERROR - Stack trace =   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 589, in main
    app.start()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/daemon.py", line 178, in start
    self.run(*args, **kwargs)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 481, in run
    raise previous_exception
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 464, in run
    self.event_queue()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 404, in event_queue
    raise e
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 380, in event_queue
    task.handler_method()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 431, in check
    self.process_queue()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 724, in process_queue
    new_events = self.process_event(p_event=event)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 681, in process_event
    self.handle_event_process_start(p_event=p_event)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 536, in handle_event_process_start
    pinfo, updated = self.get_process_handler(p_id=p_event.processhandler).handle_event_process_start(p_event)

2021-01-18 11:52:33,524 - root - INFO - Terminated with exit code 1
```

I reverted the client to 0.3.8_80, but no change. Seems that this error is caused by the server.

Edit, interesting one: Replaced the server AND client with 0.3.8_80 (installed over it), and removed the sql lite database. The problem persists.

Last edit (maybe): The problem is caused by the flag "debug_mode=True" -> This causes an access to a (maybe) non existing object which crashes the client. Same problem on server side, of debug_mode=True:

```
2021-01-18 12:45:23,108 - App - WARNING - Propagating exception due to debug_mode=True
2021-01-18 12:45:23,108 - App - ERROR - Exception 'No row was found for one()' in run()
2021-01-18 12:45:23,108 - App - INFO - Shutting down services -- START
2021-01-18 12:45:23,108 - StatusServer - INFO - Stopping web server Web Server...
2021-01-18 12:45:23,109 - StatusServer - INFO - Sending shutdown API request 'http://0.0.0.0:5555/shutdown/a607f8b8598211eb8345a7950af959f9'
2021-01-18 12:45:23,124 - StatusServer - INFO - Waiting for the server thread to terminate
2021-01-18 12:45:23,618 - StatusServer - INFO - HTTP server 'Web Server' shut down successfully
2021-01-18 12:45:23,619 - AppControl - INFO - Artificially terminating 0 active processes on ClientProcessHandler
2021-01-18 12:45:23,620 - AppControl - INFO - Artificially terminating 3 active processes on ClientDeviceHandler
2021-01-18 12:45:23,620 - AppControl - DEBUG - Queue locally: AdminEvent (type=PROCESS_END, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 12:45:23,621 - AppControl - DEBUG - Queue locally: AdminEvent (type=PROCESS_END, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 12:45:23,621 - AppControl - DEBUG - Queue locally: AdminEvent (type=PROCESS_END, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 12:45:23,622 - AppControl - DEBUG - Processing AdminEvent (type=PROCESS_END, host=yyy, user=xxx, process=None, PID=-)
2021-01-18 12:45:23,622 - ClientDeviceHandler - DEBUG - TERMINATED ProcessInfo (host=yyy, user=xxx, process=None, PID=[None], epoch=1610969592)
2021-01-18 12:45:23,633 - App - ERROR - Exception 'No row was found for one()' while stopping services
2021-01-18 12:45:23,633 - root - CRITICAL - No row was found for one()
2021-01-18 12:45:23,639 - root - ERROR - Stack trace =   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 589, in main
    app.start()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/daemon.py", line 178, in start
    self.run(*args, **kwargs)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 481, in run
    raise previous_exception
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 464, in run
    self.event_queue()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 404, in event_queue
    raise e
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/base_app.py", line 380, in event_queue
    task.handler_method()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 422, in check
    self.process_queue()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 724, in process_queue
    new_events = self.process_event(p_event=event)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 687, in process_event
    self.handle_event_process_end(p_event=p_event)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/app_control.py", line 573, in handle_event_process_end
    self._persistence.update_process_info(p_process_info=pinfo)
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/persistence.py", line 801, in update_process_info
    pinfo = session.query(ProcessInfo).filter(ProcessInfo.key == p_process_info.get_key()).one()
  File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
```

**Comment by marcus67** [comment] 2021-01-18 22:18
This report has two aspects: 

a) There is probably a bug somewhere causing the message orm_exc.NoResultFound("No row was found for one()"). It looks like a SQL select returning an empty result set when actually at least one row was expected.
b) DebugMode causes the application to "crash": This is actually intentional. I use the debug mode to make sure to get a full stack trace when an error occurs during development. Also, the application exits after reporting the error. In normal mode the error is caught in the outermost loop and ignored (except for a short error message). I'm pretty sure that the error also occurs in normal mode it's just as visible. If you can spare a moment, could you check? Thanks a lot!

**Comment by MrFly** [comment] 2021-01-18 22:23
@marcus67 you're right: I saw the error with one(), but the app stays alive (second error). But the first stacktrace (with the crash) does not happen in normal mode.

**Comment by marcus67** [comment] 2021-01-18 22:31
Thanks for testing!

**Comment by marcus67** [comment] 2021-02-05 22:05
The original was probably caused by a persisted start event for a handler that was no longer registered. This was fixed by issuing a warning and discarding the event instead.

**Closed** 2021-02-06 00:27 UTC
Labels: bug
